"""Empirical functional-gradient descent steps for the stable-tiny harness.

This module deliberately lives in ``stable_tiny`` rather than in ``gromo``.  It
uses the current DAG/MLP as the representation of admissible functional changes
and certifies each batch step against the paper's relative-error condition in
the finite empirical output space of that batch.
"""

from __future__ import annotations

from collections import OrderedDict
from dataclasses import dataclass
from typing import Callable

import torch

try:
    from torch.func import functional_call, jvp
except ImportError:  # pragma: no cover - depends on installed torch.
    functional_call = None
    jvp = None


@dataclass
class FunctionalStepInfo:
    certified: bool
    loss: float
    relative_error: float
    error_bound: float
    approx_norm: float
    cg_iterations: int
    reason: str = ""


@dataclass
class FunctionalEpochInfo:
    loss: float
    batches: int
    certified_batches: int
    failed: bool
    failure: FunctionalStepInfo | None
    max_relative_error: float
    mean_relative_error: float


def certified_functional_step(
    model: torch.nn.Module,
    x: torch.Tensor,
    y: torch.Tensor,
    loss_fn: torch.nn.Module,
    *,
    lr: float,
    damping: float,
    relative_error_tolerance: float,
    cg_min_iter: int,
    cg_max_iter: int,
    cg_tolerance: float,
    weight_decay: float = 0.0,
    grad_clip: float | None = None,
) -> FunctionalStepInfo:
    """Apply one certified projected functional-gradient step.

    The ideal target is ``dL / df`` on this batch.  The approximating family is
    the tangent space generated by the current model parameters.  The step is
    accepted only when ``(1 + eps) U < eps ||g||`` with ``U`` measured exactly in
    batch output space.
    """
    if functional_call is None or jvp is None:
        raise RuntimeError(
            "Certified functional descent requires torch.func.functional_call "
            "and torch.func.jvp."
        )
    if not (0.0 < relative_error_tolerance < 1.0):
        raise ValueError(
            "relative_error_tolerance must be in (0, 1), got "
            f"{relative_error_tolerance}"
        )
    if cg_min_iter < 1 or cg_max_iter < cg_min_iter:
        raise ValueError(
            f"Expected 1 <= cg_min_iter <= cg_max_iter, got "
            f"{cg_min_iter=} and {cg_max_iter=}"
        )

    model.zero_grad(set_to_none=True)
    named_parameters = OrderedDict(
        (name, parameter)
        for name, parameter in model.named_parameters()
        if parameter.requires_grad
    )
    if not named_parameters:
        output = model(x)
        loss = loss_fn(output, y)
        return FunctionalStepInfo(
            certified=False,
            loss=float(loss.detach()),
            relative_error=float("inf"),
            error_bound=float("inf"),
            approx_norm=0.0,
            cg_iterations=0,
            reason="model has no trainable parameters",
        )

    parameter_names = tuple(named_parameters.keys())
    parameters = tuple(named_parameters.values())
    buffers = OrderedDict(model.named_buffers())

    def call_with_parameters(parameter_values: tuple[torch.Tensor, ...]) -> torch.Tensor:
        state = OrderedDict(zip(parameter_names, parameter_values))
        state.update(buffers)
        return functional_call(model, state, (x,))

    output = model(x)
    loss = loss_fn(output, y)
    true_gradient = torch.autograd.grad(loss, output, retain_graph=True)[0].detach()
    flat_true_gradient = true_gradient.reshape(-1)
    true_norm = torch.linalg.norm(flat_true_gradient)
    if true_norm <= torch.finfo(flat_true_gradient.dtype).eps:
        return FunctionalStepInfo(
            certified=True,
            loss=float(loss.detach()),
            relative_error=0.0,
            error_bound=0.0,
            approx_norm=0.0,
            cg_iterations=0,
            reason="zero functional gradient",
        )

    def tangent_kernel_matvec(vector: torch.Tensor) -> torch.Tensor:
        structured_vector = vector.reshape_as(output)
        vjp_tensors = torch.autograd.grad(
            output,
            parameters,
            grad_outputs=structured_vector,
            retain_graph=True,
            allow_unused=True,
        )
        tangents = tuple(
            torch.zeros_like(parameter) if tangent is None else tangent.detach()
            for parameter, tangent in zip(parameters, vjp_tensors)
        )
        _, tangent_output = jvp(
            call_with_parameters,
            (parameters,),
            (tangents,),
        )
        return tangent_output.reshape(-1).detach()

    def damped_tangent_kernel_matvec(vector: torch.Tensor) -> torch.Tensor:
        return tangent_kernel_matvec(vector) + damping * vector

    best_info: FunctionalStepInfo | None = None
    accepted_solution: torch.Tensor | None = None
    accepted_iterations = 0
    for max_iter in _cg_refinement_schedule(cg_min_iter, cg_max_iter):
        solution, used_iterations = _conjugate_gradient(
            damped_tangent_kernel_matvec,
            flat_true_gradient,
            max_iter=max_iter,
            tolerance=cg_tolerance,
        )
        approx_gradient = tangent_kernel_matvec(solution)
        info = _certificate(
            loss=loss,
            approx_gradient=approx_gradient,
            true_gradient=flat_true_gradient,
            eps=relative_error_tolerance,
            cg_iterations=used_iterations,
        )
        best_info = info
        if info.certified:
            accepted_solution = solution
            accepted_iterations = used_iterations
            break

    if accepted_solution is None:
        assert best_info is not None
        best_info.reason = "relative-error certificate failed"
        return best_info

    parameter_gradients = torch.autograd.grad(
        output,
        parameters,
        grad_outputs=accepted_solution.reshape_as(output),
        retain_graph=False,
        allow_unused=True,
    )
    for parameter, parameter_gradient in zip(parameters, parameter_gradients):
        if parameter_gradient is not None:
            parameter.grad = parameter_gradient.detach()

    if grad_clip is not None:
        torch.nn.utils.clip_grad_norm_(parameters, grad_clip)

    with torch.no_grad():
        for parameter in parameters:
            if parameter.grad is None:
                continue
            if weight_decay != 0.0:
                parameter.mul_(1.0 - lr * weight_decay)
            parameter.add_(parameter.grad, alpha=-lr)

    assert best_info is not None
    best_info.cg_iterations = accepted_iterations
    return best_info


def functional_descent_epoch(
    model: torch.nn.Module,
    train_loader: torch.utils.data.DataLoader,
    loss_fn: torch.nn.Module,
    *,
    device: torch.device,
    lr: float,
    damping: float,
    relative_error_tolerance: float,
    cg_min_iter: int,
    cg_max_iter: int,
    cg_tolerance: float,
    weight_decay: float = 0.0,
    grad_clip: float | None = None,
    batch_limit: int | None = None,
    progress_every: int | None = None,
) -> FunctionalEpochInfo:
    """Run certified functional descent until an uncertified batch is found."""
    model.train()
    losses: list[float] = []
    relative_errors: list[float] = []
    certified_batches = 0
    batches = 0
    failure = None

    for batch_idx, (x, y) in enumerate(train_loader):
        if batch_limit is not None and batch_idx >= batch_limit:
            break
        batches += 1
        if progress_every is not None and progress_every > 0:
            if batch_idx % progress_every == 0:
                total = batch_limit if batch_limit is not None else len(train_loader)
                print(
                    f"    functional batch {batch_idx + 1}/{total} "
                    f"(cg_max={cg_max_iter})",
                    flush=True,
                )
        x, y = x.to(device), y.to(device)
        info = certified_functional_step(
            model,
            x,
            y,
            loss_fn,
            lr=lr,
            damping=damping,
            relative_error_tolerance=relative_error_tolerance,
            cg_min_iter=cg_min_iter,
            cg_max_iter=cg_max_iter,
            cg_tolerance=cg_tolerance,
            weight_decay=weight_decay,
            grad_clip=grad_clip,
        )
        losses.append(info.loss)
        relative_errors.append(info.relative_error)
        if not info.certified:
            if progress_every is not None and progress_every > 0:
                print(
                    f"      failed rel_err={info.relative_error:.3g} "
                    f"cg={info.cg_iterations} reason={info.reason}",
                    flush=True,
                )
            failure = info
            break
        certified_batches += 1
        if progress_every is not None and progress_every > 0:
            if batch_idx % progress_every == 0:
                print(
                    f"      certified rel_err={info.relative_error:.3g} "
                    f"cg={info.cg_iterations}",
                    flush=True,
                )

    finite_relative_errors = [
        value for value in relative_errors if value != float("inf")
    ]
    return FunctionalEpochInfo(
        loss=sum(losses) / max(1, len(losses)),
        batches=batches,
        certified_batches=certified_batches,
        failed=failure is not None,
        failure=failure,
        max_relative_error=max(relative_errors) if relative_errors else 0.0,
        mean_relative_error=(
            sum(finite_relative_errors) / len(finite_relative_errors)
            if finite_relative_errors
            else float("inf")
            if relative_errors
            else 0.0
        ),
    )


def _certificate(
    *,
    loss: torch.Tensor,
    approx_gradient: torch.Tensor,
    true_gradient: torch.Tensor,
    eps: float,
    cg_iterations: int,
) -> FunctionalStepInfo:
    error = torch.linalg.norm(approx_gradient - true_gradient)
    approx_norm = torch.linalg.norm(approx_gradient)
    if approx_norm <= torch.finfo(approx_gradient.dtype).eps:
        return FunctionalStepInfo(
            certified=False,
            loss=float(loss.detach()),
            relative_error=float("inf"),
            error_bound=float(error.detach()),
            approx_norm=0.0,
            cg_iterations=cg_iterations,
            reason="zero approximate gradient",
        )

    relative_error = error / approx_norm
    certified = bool((1.0 + eps) * error < eps * approx_norm)
    return FunctionalStepInfo(
        certified=certified,
        loss=float(loss.detach()),
        relative_error=float(relative_error.detach()),
        error_bound=float(error.detach()),
        approx_norm=float(approx_norm.detach()),
        cg_iterations=cg_iterations,
    )


def _cg_refinement_schedule(min_iter: int, max_iter: int) -> list[int]:
    values = []
    current = min_iter
    while current < max_iter:
        values.append(current)
        current *= 2
    values.append(max_iter)
    return values


def _conjugate_gradient(
    matvec: Callable[[torch.Tensor], torch.Tensor],
    rhs: torch.Tensor,
    *,
    max_iter: int,
    tolerance: float,
) -> tuple[torch.Tensor, int]:
    solution = torch.zeros_like(rhs)
    residual = rhs.clone()
    direction = residual.clone()
    rhs_norm = torch.linalg.norm(rhs).clamp_min(torch.finfo(rhs.dtype).eps)
    residual_inner = torch.dot(residual, residual)

    for iteration in range(1, max_iter + 1):
        matvec_direction = matvec(direction)
        curvature = torch.dot(direction, matvec_direction)
        if curvature.abs() <= torch.finfo(rhs.dtype).eps:
            return solution, iteration

        step_size = residual_inner / curvature
        solution = solution + step_size * direction
        residual = residual - step_size * matvec_direction
        if torch.linalg.norm(residual) / rhs_norm <= tolerance:
            return solution, iteration

        next_residual_inner = torch.dot(residual, residual)
        beta = next_residual_inner / residual_inner.clamp_min(
            torch.finfo(rhs.dtype).eps
        )
        direction = residual + beta * direction
        residual_inner = next_residual_inner

    return solution, max_iter
